# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Stuart Clark"

# Tagline next to the site title
tagline: "Strong opinions, loosely held."

# A description of your site for social meta tag, search engines, and feed.xml
description: "A site about coding, architecture and adventure."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

# Sass
sass:
  sass_dir: _sass
  style: compressed

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://stuartclark.co.nz"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Archives
    url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: "justgoodthemes"

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "UA-173581581-2"

# Author information - author info at the bottom of the post
author_name: "Stuart Clark"
author_bio: "Stuart is a developer, coding architect and general outdoor enthusiast."
# author_url: "http://justgoodthemes.com"
author_location: "Wellington, New Zealand"
author_image: /images/author.jpg

# Sidebar Add banner
#banner_url: "https://justgoodthemes.com"
#banner_image: images/banner.jpg
#banner_image_alt: "Alt text"

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_url: "https://twitter.com/"
#facebook_url: "https://www.facebook.com/"
github_url: "https://github.com/sjclark76"
#codepen_url: "https://codepen.io/"
#dribbble_url: "https://dribbble.com/"
#medium_url: "https://medium.com/"
#instagram_url: "https://www.instagram.com/"
#pinterest_url: "https://www.pinterest.com/"
linkedin_url: "https://www.linkedin.com/in/stuart-clark-8320282a/"
#weibo_url: "https://www.weibo.com/"

# http://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: false
